include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "build/**"
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - always_declare_return_types
    - always_use_package_imports
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_unused_constructor_parameters
    - cascade_invocations
    - directives_ordering
    - omit_local_variable_types
    - only_throw_errors
    - prefer_const_constructors
    - prefer_final_locals
    - prefer_single_quotes
    - sort_constructors_first
    - sort_pub_dependencies
    - unnecessary_late
    - use_super_parameters