name: hold_that_thought
description: >
  Hold That Thought is a cross-platform Flutter application for capturing and organising
  fleeting thoughts with voice or text, including a 10‑second pre‑roll buffer for speech
  before recording starts. It supports cloud sync, transcription, categorisation,
  reminders and export features via Free and Pro tiers.
version: 0.1.0
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_riverpod: ^2.3.6
  go_router: ^13.0.1
  url_strategy: ^0.3.0
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  record: ^5.0.7
  just_audio: ^0.9.35
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_local_notifications: ^17.1.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_crashlytics: ^5.0.0
  firebase_analytics: ^12.0.0
  firebase_remote_config: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences_platform_interface: ^2.4.1
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  hive_generator: ^2.0.1
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.6
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/branding/

flutter_native_splash:
  color: "#42a5f5"
  image: assets/branding/splash.png