name: hold_that_thought
description: >
  Hold That Thought is a cross-platform Flutter application for capturing and organising
  fleeting thoughts with voice or text, including a 10‑second pre‑roll buffer for speech
  before recording starts. It supports cloud sync, transcription, categorisation,
  reminders and export features via Free and Pro tiers.
version: 0.1.0
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^13.0.1

  # Local persistence with Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Other utilities
  path_provider: ^2.0.11
  intl: ^0.18.1
  uuid: ^4.3.3

  # Firebase and audio packages (retained for future use)
  record: ^5.0.7
  just_audio: ^0.9.35
  isar: ^4.0.0
  isar_flutter_libs: ^4.0.0
  flutter_local_notifications: ^17.1.1
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.5.0
  firebase_crashlytics: ^3.6.0
  firebase_analytics: ^13.5.0
  firebase_remote_config: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  isar_generator: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/