name: CI Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  frontend-ci:
    name: Frontend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'
          cache: true

      - name: Install Frontend Dependencies
        run: flutter pub get

      - name: Analyze Dart Code (Lint)
        run: flutter analyze

      - name: Check Formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Run Unit & Widget Tests
        run: flutter test

      - name: Build Web App
        run: flutter build web --release

  backend-ci:
    name: Backend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'functions/package-lock.json'

      - name: Install Backend Dependencies
        run: npm ci

      - name: Check Linting
        run: npm run lint

      - name: Check Formatting
        # Add --check flag to the format script to prevent writes
        run: npm run format -- --check