name: CI

on:
  push:
    branches: ['**']
    tags: ['v*']
  pull_request:
    branches: ['**']
  workflow_dispatch: {}

env:
  VERSION_NAME_FROM_TAG: ${{ startsWith(github.ref, 'refs/tags/v') && !contains(github.ref_name, '-rc') && replace(github.ref_name, 'v', '') || '' }}
  VERSION_CODE_FROM_RUN: ${{ github.run_number }}

jobs:
  build_android:
    name: Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: android-actions/setup-android@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Accept licenses
        run: yes | sdkmanager --licenses || true
      - name: Install SDK components
        run: |
          SDK=34
          sdkmanager "platforms;android-$SDK" "build-tools;${SDK}.0.0" "platform-tools" || true
      - name: Flutter pub get
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 30

  build_windows:
    name: Windows ZIP
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop
      - name: Flutter pub get
        run: flutter pub get
      - name: Build Windows
        run: flutter build windows --release
      - name: Create ZIP
        shell: bash
        run: |
          cd build/windows/x64/runner/Release
          7z a -tzip ../../../../windows-build.zip ./*
      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: windows-zip
          path: build/windows-build.zip
          retention-days: 30

  release:
    name: GitHub Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build_android, build_windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: dist
      - uses: actions/download-artifact@v4
        with:
          name: windows-zip
          path: dist
      - name: Rename files
        run: |
          cd dist
          mv app-debug.apk "HoldThatThought-${{ github.ref_name }}-debug.apk"
          mv windows-build.zip "HoldThatThought-${{ github.ref_name }}-windows.zip"
      - name: Generate checksums
        run: |
          cd dist
          sha256sum *.apk > "HoldThatThought-${{ github.ref_name }}-debug.apk.sha256"
          sha256sum *.zip > "HoldThatThought-${{ github.ref_name }}-windows.zip.sha256"
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/HoldThatThought-${{ github.ref_name }}-debug.apk
            dist/HoldThatThought-${{ github.ref_name }}-debug.apk.sha256
            dist/HoldThatThought-${{ github.ref_name }}-windows.zip
            dist/HoldThatThought-${{ github.ref_name }}-windows.zip.sha256
          draft: false
          prerelease: ${{ contains(github.ref_name, '-rc') }}