name: CI-Simple
on:
  push:
    branches: ['**']
    tags: ['v*']
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test from $GITHUB_REF ($GITHUB_SHA)"
      
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: echo "Creating release for ${{ github.ref_name }}"
      - uses: softprops/action-gh-release@v2
        with:
          body: "Automated release for ${{ github.ref_name }}"