name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

env:
  COVERAGE_MIN: "60"

jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
      
      - name: Analyze project source
        run: flutter analyze
      
      - name: Run tests
        run: flutter test --coverage
      
      - name: Check Vector index tests
        run: flutter test test/vector_index_test.dart
      
      - name: Check Crypto service tests
        run: flutter test test/crypto_service_test.dart
        
      - name: Enforce coverage thresholds
        run: |
          sudo apt-get update && sudo apt-get install -y lcov
          TOTAL=$(lcov --summary coverage/lcov.info | awk '/lines/ {print $2}' | tr -d '%')
          THRESH=${COVERAGE_MIN}
          echo "Total coverage: $TOTAL%"
          echo "Required minimum: $THRESH%"
          awk 'BEGIN{ if('"$TOTAL"' < '"$THRESH"') exit 1 }'
      
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage/lcov.info

  build_windows:
    name: Build Windows App
    needs: lint_and_test
    runs-on: windows-latest
    timeout-minutes: 60
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Enable Windows
        run: flutter config --enable-windows-desktop
      
      - name: Build Windows
        run: flutter build windows --release
      
      - name: Create .env file
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > build/windows/runner/Release/.env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> build/windows/runner/Release/.env
          echo "FEATURE_AUTH_ENABLED=false" >> build/windows/runner/Release/.env
          echo "FEATURE_RAG_ENABLED=false" >> build/windows/runner/Release/.env
          echo "FEATURE_E2EE_ENABLED=false" >> build/windows/runner/Release/.env
          echo "FEATURE_TELEMETRY_ENABLED=false" >> build/windows/runner/Release/.env
      
      - name: Create zip archive
        run: |
          cd build/windows/runner/Release
          7z a -tzip ../../../windows-release.zip *
      
      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: build/windows-release.zip
          retention-days: 7

  build_android:
    name: Build Android App
    needs: lint_and_test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Create .env file
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > android/app/src/main/assets/.env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> android/app/src/main/assets/.env
          echo "FEATURE_AUTH_ENABLED=false" >> android/app/src/main/assets/.env
          echo "FEATURE_RAG_ENABLED=false" >> android/app/src/main/assets/.env
          echo "FEATURE_E2EE_ENABLED=false" >> android/app/src/main/assets/.env
          echo "FEATURE_TELEMETRY_ENABLED=false" >> android/app/src/main/assets/.env
      
      - name: Build Android Debug APK
        run: flutter build apk --debug
      
      - name: Upload Android Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 7
