name: Flutter CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'   # pin to the project’s version
          channel: 'stable'
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Use Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache pub + tool dirs
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            **/.dart_tool
          key: pub-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            pub-${{ runner.os }}-

      - name: Get packages
        run: flutter pub get

      - name: Generate localization (best effort)
        run: flutter gen-l10n
        continue-on-error: true

      - name: Build generated sources if used
        run: |
          if grep -R --quiet "build_runner" pubspec.lock; then
            flutter pub run build_runner build --delete-conflicting-outputs
          fi
        continue-on-error: true

      - name: Run tests (verbose + coverage)
        env:
          CI: true
          LC_ALL: C.UTF-8
          LANG: C.UTF-8
        run: flutter test --coverage --reporter expanded --verbose

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage/lcov.info

      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            .dart_tool
            **/test_outputs/**/*
            **/flutter_*.log
