name: Play Promote
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to promote (e.g., v0.10.5)"
        required: true
      track_from:
        description: "Source track"
        required: false
        default: "internal"
      track_to:
        description: "Target track (closed|production)"
        required: true
        default: "closed"
      user_fraction:
        description: "Rollout fraction (0.1,0.25,0.5,1)"
        required: true
        default: "0.1"
      release_notes:
        description: "What's new (optional)"
        required: false
        default: ""
permissions:
  contents: read
jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare what's new
        run: |
          mkdir -p dist/whatsnew
          file="dist/CHANGELOG-${{ inputs.tag }}.md"
          [ -f "$file" ] || echo "${{ inputs.release_notes }}" > "$file"
          head -c 500 "$file" | tr -d '\r' > dist/whatsnew/en-US.txt
      - name: Promote to ${{ inputs.track_to }}
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: ${{ secrets.PLAY_PACKAGE_NAME }}
          track: ${{ inputs.track_to }}
          status: inProgress
          userFraction: ${{ inputs.user_fraction }}
          whatsNewDirectory: dist/whatsnew