name: release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate coverage summary (best effort)
        run: |
          flutter pub get || true
          flutter test --coverage --test-randomize-ordering-seed=random || true
          mkdir -p docs
          echo "# Release Coverage Snapshot" > docs/RELEASE_COVERAGE.md
          echo "" >> docs/RELEASE_COVERAGE.md
          if [[ -f coverage/lcov.info ]]; then
            awk '/^SF:/{file=$0}/^end_of_record/{print file}' coverage/lcov.info >/dev/null 2>&1 || true
          fi

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
