name: Secret Scan
on: 
  push:
  pull_request:
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Block .env in repo
        run: |
          if [ -f ".env" ]; then
            echo "::error::.env must not be committed"; exit 1; fi
      - name: Run gitleaks
        uses: zricethezav/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
